version: '3.1'
services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aicareer
      MYSQL_ROOT_PASSWORD: aicareer
      MYSQL_USER: aicareer
      MYSQL_PASSWORD: aicareer
