version: '3.1'
services:
  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: aicareer
      MYSQL_ROOT_PASSWORD: aicareer
      MYSQL_USER: aicareer
      MYSQL_PASSWORD: aicareer
  web:
    image: sweun2/aicareer-dev:aicareer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aicareer
      SPRING_DATASOURCE_USERNAME: aicareer
      SPRING_DATASOURCE_PASSWORD: aicareer
    depends_on:
      - mariadb
    restart: always
    ports:
      - "8080:8080"
