spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include:
      - "oauth"
      - "aws"

---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod