spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    include:
      - "aws"
      - "email"
      - "clova"

nickname: "./nickname-list.txt"




---
spring:
  profiles:
    active: local



---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod