spring-doc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /**
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/aicareerdev
    username: aicareerdev
    password: aicareer!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        javax:
          persistence:
            lock:
              timeout=5000
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 47627470600-dgjrp1bb3c4rpqkft51rqujs2l43t2gm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "https://api.aicareer.co.kr/login/oauth2/code/google"
            scope:
              - email
              - profile
          naver:
            client-id: 9k0TW8aTgCZZS6I23DCE
            client-secret: JJMmEJFgtA
            redirect-uri: "https://dev.aicareer.co.kr/login/oauth2/code/naver"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 567a3bba3ec24bb1cabaadaab32a2325
            client-secret: tjIU8hKzP3G3MHOR4f2yoA5i2qMnd1oY
            redirect-uri: "https://dev.aicareer.co.kr/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 80
  ssl.key-store-type: PKCS12
  ssl.key-store: classpath:ssl.p12
  ssl.key-store-password: aicareer!
  error:
    include-message: always
logging:
  level:
    org:
      springframework: DEBUG
back-url: "https://dev.aicareer.co.kr"
front-url: "https://alpha.aicareer.co.kr"
front-url-not-protocol: "alpha.aicareer.co.kr"
back-url-not-protocol: "dev.aicareer.co.kr"
jwt:
  secret_key: "안녕하세요. 국내 최초 인공지능 직무 채용 플랫폼 AIcareer입니다. 당신의 AI 커리어를 위한 최신 채용 공고를 매일 업데이트하여 제공합니다. "
