spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    include:
      - "aws"
      - "email"
      - "clova"



---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: dev


---
spring:
  profiles:
    active: local