spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: "unlearningdev"
    password: "ptyewutlmxbhrpqm"
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            require: true
    protocol: smtps
