spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: aY6ehque07j5CjYTBIcX
            client-secret: 73CHBBQ3sD
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 567a3bba3ec24bb1cabaadaab32a2325
            client-secret: tjIU8hKzP3G3MHOR4f2yoA5i2qMnd1oY
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret_key: "힘을 내라고 말해 줄래 그 눈을 반짝여 날 일으켜 줄래 사람들은 모두 원하지 더 빨리 더 많이 Oh 난 평범한 소년걸"
