clova:
  ocr:
    api-url: "https://ylbt86lwm9.apigw.ntruss.com/custom/v1/31011/e9ad03714eb0ba98b196bff13ca8ff3e76cb548d2094427d1ec0c6ca97fcc492/general"
    secret: "RGZIS1h2b1ZzcWhLdXZuQ0hQYVJFQkNkdU9IenNjeXg="
