spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    include:
      - "aws"
      - "email"

---
spring:
  profiles:
    active: local


---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: dev