spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include:
      - "aws"
      - "email"
      - "clova"
      - "openai"

nickname: "./nickname-list.txt"
s3-url: "aicareer-image-bucket.s3.ap-northeast-2.amazonaws.com"


---
spring:
  profiles:
    active: dev


---
spring:
  profiles:
    active: local


---
spring:
  profiles:
    active: prod