spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 47627470600-dgjrp1bb3c4rpqkft51rqujs2l43t2gm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "https://api.aicareer.co.kr/login/oauth2/code/google"
            scope:
              - email
              - profile
          naver:
            client-id: aY6ehque07j5CjYTBIcX
            client-secret: 73CHBBQ3sD
            redirect-uri: "https://api.aicareer.co.kr/login/oauth2/code/naver"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 567a3bba3ec24bb1cabaadaab32a2325
            client-secret: tjIU8hKzP3G3MHOR4f2yoA5i2qMnd1oY
            redirect-uri: "https://api.aicareer.co.kr/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret_key: "안녕하세요. 국내 최초 인공지능 직무 채용 플랫폼 AIcareer입니다. 당신의 AI 커리어를 위한 최신 채용 공고를 매일 업데이트하여 제공합니다. "
